"""empty message

Revision ID: 49290e9d1ab8
Revises: 3c3cd1268a2f
Create Date: 2022-02-25 22:18:48.530032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49290e9d1ab8'
down_revision = '3c3cd1268a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movies', sa.String(length=64), nullable=True))
    op.alter_column('movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('movies', 'movie_title')
    op.drop_column('movies', 'image_url')
    op.drop_column('movies', 'movie_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('movie_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('movies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('movies', 'movies')
    # ### end Alembic commands ###
