"""empty message

Revision ID: 855824996112
Revises: 49290e9d1ab8
Create Date: 2022-02-25 22:23:51.251971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855824996112'
down_revision = '49290e9d1ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_title', sa.String(length=64), nullable=True))
    op.add_column('movies', sa.Column('movie_url', sa.String(length=200), nullable=True))
    op.add_column('movies', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.drop_column('movies', 'movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movies', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('movies', 'image_url')
    op.drop_column('movies', 'movie_url')
    op.drop_column('movies', 'movie_title')
    # ### end Alembic commands ###
